USE [master]
GO

CREATE DATABASE [FeatureDB]

ALTER DATABASE [FeatureDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FeatureDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FeatureDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FeatureDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FeatureDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [FeatureDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [FeatureDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FeatureDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FeatureDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FeatureDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FeatureDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FeatureDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FeatureDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FeatureDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FeatureDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [FeatureDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FeatureDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FeatureDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FeatureDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FeatureDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FeatureDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FeatureDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FeatureDB] SET RECOVERY FULL 
GO
ALTER DATABASE [FeatureDB] SET  MULTI_USER 
GO
ALTER DATABASE [FeatureDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FeatureDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FeatureDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FeatureDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [FeatureDB] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'FeatureDB', N'ON'
GO
ALTER DATABASE [FeatureDB] SET QUERY_STORE = OFF
GO
USE [FeatureDB]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[userProfileTbl](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [varchar](100) NOT NULL,
	[Firstname] [varchar](100) NOT NULL,
	[LastName] [varchar](100) NOT NULL,
	[Email] [varchar](50) NOT NULL,
	[Password] [varchar](50) NOT NULL,
	[IsActive] [bit] NOT NULL,
	[IsDeleted] [bit] NOT NULL,
	[CreatedOn] [datetime] NOT NULL,
	[CreatedBy] [varchar](100) NULL,
	[LastModifiedOn] [datetime] NULL,
	[LastModifiedBy] [varchar](100) NULL,
 CONSTRAINT [PK_userTbl] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[userProfileTbl] ADD  CONSTRAINT [DF_userProfileTbl_IsDeleted]  DEFAULT ((0)) FOR [IsDeleted]
GO
USE [master]
GO
ALTER DATABASE [FeatureDB] SET  READ_WRITE 
GO

alter table userProfileTbl Add RefreshToken varchar(100);