CREATE OR ALTER FUNCTION GENERATEUNIQUEUSERID()
RETURNS  NVARCHAR(100) 
AS
BEGIN
DECLARE @LastUserID NVARCHAR(100)
SELECT top 1 @LastUserID=UserId from dbo.userProfileTbl ORDER BY Id DESC
RETURN CONCAT('QE',CAST(TRIM('QE' FROM @LastUserID) AS BIGINT) +1)
END